version: '3.8'

services:
  app:
    image: mogreene-app
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_SSL_ENABLED=true
      - TZ=Asia/Seoul
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    networks:
      - backend

networks:
  backend:
    driver: bridge