server:
  servlet:
    context-path: /v1

spring:
  profiles:
    include: prod, aws, secret

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace